// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminDashboard struct {
	Catalog   *CatalogSnapshot  `json:"catalog"`
	Customers *CustomerSnapshot `json:"customers"`
}

type Book struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Author     string `json:"author"`
	Isbn       string `json:"isbn"`
	PriceCents int64  `json:"priceCents"`
	Stock      int32  `json:"stock"`
	SellerID   string `json:"sellerId"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type BookDetail struct {
	Book     *Book              `json:"book"`
	Comments *CommentConnection `json:"comments"`
}

// Statistics cover only the requested cursor page; they are never presented as global totals.
type CatalogSnapshot struct {
	LoadedCount         int32     `json:"loadedCount"`
	InventoryUnits      int64     `json:"inventoryUnits"`
	LowStockCount       int32     `json:"lowStockCount"`
	InventoryValueCents int64     `json:"inventoryValueCents"`
	RecentBooks         []*Book   `json:"recentBooks"`
	LowStockBooks       []*Book   `json:"lowStockBooks"`
	PageInfo            *PageInfo `json:"pageInfo"`
}

type Comment struct {
	ID         string  `json:"id"`
	BookID     string  `json:"bookId"`
	AuthorID   string  `json:"authorId"`
	AuthorName string  `json:"authorName"`
	ParentID   *string `json:"parentId,omitempty"`
	RootID     string  `json:"rootId"`
	Depth      int32   `json:"depth"`
	Content    string  `json:"content"`
	Status     string  `json:"status"`
	ReplyCount int64   `json:"replyCount"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type CommentConnection struct {
	Nodes    []*Comment `json:"nodes"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Customer struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type CustomerSnapshot struct {
	LoadedCount     int32       `json:"loadedCount"`
	RecentCustomers []*Customer `json:"recentCustomers"`
	PageInfo        *PageInfo   `json:"pageInfo"`
}

type Order struct {
	ID                   string       `json:"id"`
	UserID               string       `json:"userId"`
	Status               string       `json:"status"`
	TotalCents           int64        `json:"totalCents"`
	Currency             string       `json:"currency"`
	Items                []*OrderItem `json:"items"`
	PaymentID            *string      `json:"paymentId,omitempty"`
	FailureReason        *string      `json:"failureReason,omitempty"`
	ReservationExpiresAt *string      `json:"reservationExpiresAt,omitempty"`
	CreatedAt            string       `json:"createdAt"`
	UpdatedAt            string       `json:"updatedAt"`
}

type OrderDetail struct {
	Order   *Order   `json:"order"`
	Payment *Payment `json:"payment,omitempty"`
}

type OrderItem struct {
	ID             string `json:"id"`
	BookID         string `json:"bookId"`
	SellerID       string `json:"sellerId"`
	Title          string `json:"title"`
	UnitPriceCents int64  `json:"unitPriceCents"`
	Quantity       int32  `json:"quantity"`
	SubtotalCents  int64  `json:"subtotalCents"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Payment struct {
	ID                    string  `json:"id"`
	OrderID               string  `json:"orderId"`
	BuyerID               string  `json:"buyerId"`
	Status                string  `json:"status"`
	AmountCents           int64   `json:"amountCents"`
	PlatformFeeCents      int64   `json:"platformFeeCents"`
	Currency              string  `json:"currency"`
	FailureReason         *string `json:"failureReason,omitempty"`
	Provider              string  `json:"provider"`
	ProviderTransactionID *string `json:"providerTransactionId,omitempty"`
	CheckoutURL           *string `json:"checkoutUrl,omitempty"`
	ExpiresAt             *string `json:"expiresAt,omitempty"`
	PaidAt                *string `json:"paidAt,omitempty"`
	CreatedAt             string  `json:"createdAt"`
	UpdatedAt             string  `json:"updatedAt"`
}

type Query struct {
}
