package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	bookstorev1 "github.com/thinhnguyenwilliam/book-store/backend/gen/bookstore/v1"
	"github.com/thinhnguyenwilliam/book-store/backend/internal/gateway/graphql/generated"
	"github.com/thinhnguyenwilliam/book-store/backend/internal/gateway/graphql/model"
	"golang.org/x/sync/errgroup"
)

// BookDetail is the resolver for the bookDetail field.
func (r *queryResolver) BookDetail(ctx context.Context, id string, commentsFirst *int32, commentsAfter *string) (*model.BookDetail, error) {
	limit, err := pageLimit(commentsFirst, 10)
	if err != nil {
		return nil, err
	}
	var book *bookstorev1.Book
	var comments *bookstorev1.ListCommentsResponse
	group, groupCtx := errgroup.WithContext(ctx)
	group.Go(func() error {
		var callErr error
		book, callErr = r.Books.GetBook(groupCtx, &bookstorev1.GetBookRequest{Id: id})
		return callErr
	})
	group.Go(func() error {
		var callErr error
		comments, callErr = r.Comments.ListBookComments(groupCtx, &bookstorev1.ListBookCommentsRequest{
			BookId: id, Limit: limit, Cursor: stringValue(commentsAfter),
		})
		return callErr
	})
	if err := group.Wait(); err != nil {
		return nil, grpcGraphError(err)
	}
	nodes := make([]*model.Comment, 0, len(comments.GetComments()))
	for _, item := range comments.GetComments() {
		nodes = append(nodes, commentModel(item))
	}
	return &model.BookDetail{
		Book: bookModel(book),
		Comments: &model.CommentConnection{Nodes: nodes, PageInfo: &model.PageInfo{
			HasNextPage: comments.GetHasMore(), EndCursor: optionalString(comments.GetNextCursor()),
		}},
	}, nil
}

// AdminDashboard is the resolver for the adminDashboard field.
func (r *queryResolver) AdminDashboard(ctx context.Context, booksFirst *int32, booksAfter *string, customersFirst *int32, customersAfter *string) (*model.AdminDashboard, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	bookLimit, err := pageLimit(booksFirst, 20)
	if err != nil {
		return nil, err
	}
	customerLimit, err := pageLimit(customersFirst, 5)
	if err != nil {
		return nil, err
	}
	var books *bookstorev1.ListBooksResponse
	var users *bookstorev1.ListProfilesResponse
	group, groupCtx := errgroup.WithContext(ctx)
	group.Go(func() error {
		var callErr error
		books, callErr = r.Books.ListBooks(groupCtx, &bookstorev1.ListBooksRequest{Limit: bookLimit, Cursor: stringValue(booksAfter)})
		return callErr
	})
	group.Go(func() error {
		var callErr error
		users, callErr = r.Users.ListProfiles(groupCtx, &bookstorev1.ListProfilesRequest{Limit: customerLimit, Cursor: stringValue(customersAfter)})
		return callErr
	})
	if err := group.Wait(); err != nil {
		return nil, grpcGraphError(err)
	}
	customers := make([]*model.Customer, 0, len(users.GetUsers()))
	for _, item := range users.GetUsers() {
		customers = append(customers, customerModel(item))
	}
	return &model.AdminDashboard{
		Catalog: catalogSnapshot(books),
		Customers: &model.CustomerSnapshot{
			LoadedCount: int32(len(customers)), RecentCustomers: customers,
			PageInfo: &model.PageInfo{HasNextPage: users.GetHasMore(), EndCursor: optionalString(users.GetNextCursor())},
		},
	}, nil
}

// OrderDetail is the resolver for the orderDetail field.
func (r *queryResolver) OrderDetail(ctx context.Context, id string) (*model.OrderDetail, error) {
	principal, err := requireAuthenticated(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.Orders.GetOrder(ctx, &bookstorev1.GetOrderRequest{UserId: principal.UserID, Id: id})
	if err != nil {
		return nil, grpcGraphError(err)
	}
	result := &model.OrderDetail{Order: orderModel(order)}
	if order.GetPaymentId() == "" {
		return result, nil
	}
	payment, err := r.Payments.GetPayment(ctx, &bookstorev1.GetPaymentRequest{Id: order.GetPaymentId(), BuyerId: principal.UserID})
	if err != nil {
		return nil, grpcGraphError(err)
	}
	result.Payment = paymentModel(payment)
	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
